eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: 192.168.2.114:8081
    prefer-ip-address: true
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ~!QAZpl,8086
    url: jdbc:mysql://140.143.89.162:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
