spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ~!QAZpl,8086
    url: jdbc:mysql://140.143.89.162:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
